server:
  port: 6200

spring:
  application:
    #服务的名称
    name: microservice-zuul

#将zuul注册进eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6001/eureka/


#网关配置
zuul:
  routes:
    microservice-consumer: /consumer/**
    # 该配置方式中，provider-route只是给路由一个名称，可以任意起名。
    provider-route:
      service-id: microservice-provider
      # service-id对应的路径
      path: /provider/**

    consumer-route:
      service-id: microservice-consumer
      path: /consumer/**
  #不能使用原始的带服务名的方式访问
  #ignored-services: SPRINGCLOUD-PROVIDER-DEPT
  #如果服务很多,可以全部影藏
  ignored-services: '*'
  #添加统一的前缀(可以不设置)
  prefix: /api

logging:
  level:
    com.netflix: DEBUG
