server:
  servlet:
    # 项目路径
    context-path: /provider

spring:
  profiles:
    # 指定运行环境
    active: dev

  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-provider
  # 全局jackson时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  # 指定Mapper.xml文件位置,可以是数组.默认配置为'- classpath*:/mapper/**/*.xml'
  mapperLocations:
    - classpath*:/mapper/**/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  typeAliasesPackage: com.yese.provider.entity
  global-config:
    db-config:
      # 全局主键类型
      id-type: AUTO
      # 配置逻辑删除相关
      # 全局逻辑删除的实体属性名(根据实际情况配置)
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0

management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
